branch-defaults:
  master:
    environment: joboserver-env
environment-defaults:
  joboserver-env:
    branch: master
    repository: origin
global:
  application_name: joboserver
  default_ec2_keyname: joboserver
  default_platform: Node.js
  default_region: us-west-2
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
